// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.0
// source: imageproto/image.proto

package imageproto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DownloadImagesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Info          *ImageInfo             `protobuf:"bytes,1,opt,name=info,proto3" json:"info,omitempty"`
	Image         []byte                 `protobuf:"bytes,2,opt,name=image,proto3" json:"image,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DownloadImagesRequest) Reset() {
	*x = DownloadImagesRequest{}
	mi := &file_imageproto_image_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DownloadImagesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DownloadImagesRequest) ProtoMessage() {}

func (x *DownloadImagesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_imageproto_image_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DownloadImagesRequest.ProtoReflect.Descriptor instead.
func (*DownloadImagesRequest) Descriptor() ([]byte, []int) {
	return file_imageproto_image_proto_rawDescGZIP(), []int{0}
}

func (x *DownloadImagesRequest) GetInfo() *ImageInfo {
	if x != nil {
		return x.Info
	}
	return nil
}

func (x *DownloadImagesRequest) GetImage() []byte {
	if x != nil {
		return x.Image
	}
	return nil
}

type ImageInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Compress      string                 `protobuf:"bytes,1,opt,name=compress,proto3" json:"compress,omitempty"`
	Watermark     string                 `protobuf:"bytes,2,opt,name=watermark,proto3" json:"watermark,omitempty"`
	Format        string                 `protobuf:"bytes,3,opt,name=format,proto3" json:"format,omitempty"`
	Width         []int32                `protobuf:"varint,4,rep,packed,name=width,proto3" json:"width,omitempty"`
	Height        []int32                `protobuf:"varint,5,rep,packed,name=height,proto3" json:"height,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ImageInfo) Reset() {
	*x = ImageInfo{}
	mi := &file_imageproto_image_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ImageInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ImageInfo) ProtoMessage() {}

func (x *ImageInfo) ProtoReflect() protoreflect.Message {
	mi := &file_imageproto_image_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ImageInfo.ProtoReflect.Descriptor instead.
func (*ImageInfo) Descriptor() ([]byte, []int) {
	return file_imageproto_image_proto_rawDescGZIP(), []int{1}
}

func (x *ImageInfo) GetCompress() string {
	if x != nil {
		return x.Compress
	}
	return ""
}

func (x *ImageInfo) GetWatermark() string {
	if x != nil {
		return x.Watermark
	}
	return ""
}

func (x *ImageInfo) GetFormat() string {
	if x != nil {
		return x.Format
	}
	return ""
}

func (x *ImageInfo) GetWidth() []int32 {
	if x != nil {
		return x.Width
	}
	return nil
}

func (x *ImageInfo) GetHeight() []int32 {
	if x != nil {
		return x.Height
	}
	return nil
}

type DownloadImagesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StoragePath   []string               `protobuf:"bytes,1,rep,name=storage_path,json=storagePath,proto3" json:"storage_path,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DownloadImagesResponse) Reset() {
	*x = DownloadImagesResponse{}
	mi := &file_imageproto_image_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DownloadImagesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DownloadImagesResponse) ProtoMessage() {}

func (x *DownloadImagesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_imageproto_image_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DownloadImagesResponse.ProtoReflect.Descriptor instead.
func (*DownloadImagesResponse) Descriptor() ([]byte, []int) {
	return file_imageproto_image_proto_rawDescGZIP(), []int{2}
}

func (x *DownloadImagesResponse) GetStoragePath() []string {
	if x != nil {
		return x.StoragePath
	}
	return nil
}

func (x *DownloadImagesResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

var File_imageproto_image_proto protoreflect.FileDescriptor

const file_imageproto_image_proto_rawDesc = "" +
	"\n" +
	"\x16imageproto/image.proto\x12\n" +
	"imageproto\"X\n" +
	"\x15DownloadImagesRequest\x12)\n" +
	"\x04info\x18\x01 \x01(\v2\x15.imageproto.ImageInfoR\x04info\x12\x14\n" +
	"\x05image\x18\x02 \x01(\fR\x05image\"\x8b\x01\n" +
	"\tImageInfo\x12\x1a\n" +
	"\bcompress\x18\x01 \x01(\tR\bcompress\x12\x1c\n" +
	"\twatermark\x18\x02 \x01(\tR\twatermark\x12\x16\n" +
	"\x06format\x18\x03 \x01(\tR\x06format\x12\x14\n" +
	"\x05width\x18\x04 \x03(\x05R\x05width\x12\x16\n" +
	"\x06height\x18\x05 \x03(\x05R\x06height\"Q\n" +
	"\x16DownloadImagesResponse\x12!\n" +
	"\fstorage_path\x18\x01 \x03(\tR\vstoragePath\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error2i\n" +
	"\fImageService\x12Y\n" +
	"\x0eDownloadImages\x12!.imageproto.DownloadImagesRequest\x1a\".imageproto.DownloadImagesResponse(\x01B\x17Z\x15grpc_image/imageprotob\x06proto3"

var (
	file_imageproto_image_proto_rawDescOnce sync.Once
	file_imageproto_image_proto_rawDescData []byte
)

func file_imageproto_image_proto_rawDescGZIP() []byte {
	file_imageproto_image_proto_rawDescOnce.Do(func() {
		file_imageproto_image_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_imageproto_image_proto_rawDesc), len(file_imageproto_image_proto_rawDesc)))
	})
	return file_imageproto_image_proto_rawDescData
}

var file_imageproto_image_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_imageproto_image_proto_goTypes = []any{
	(*DownloadImagesRequest)(nil),  // 0: imageproto.DownloadImagesRequest
	(*ImageInfo)(nil),              // 1: imageproto.ImageInfo
	(*DownloadImagesResponse)(nil), // 2: imageproto.DownloadImagesResponse
}
var file_imageproto_image_proto_depIdxs = []int32{
	1, // 0: imageproto.DownloadImagesRequest.info:type_name -> imageproto.ImageInfo
	0, // 1: imageproto.ImageService.DownloadImages:input_type -> imageproto.DownloadImagesRequest
	2, // 2: imageproto.ImageService.DownloadImages:output_type -> imageproto.DownloadImagesResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_imageproto_image_proto_init() }
func file_imageproto_image_proto_init() {
	if File_imageproto_image_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_imageproto_image_proto_rawDesc), len(file_imageproto_image_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_imageproto_image_proto_goTypes,
		DependencyIndexes: file_imageproto_image_proto_depIdxs,
		MessageInfos:      file_imageproto_image_proto_msgTypes,
	}.Build()
	File_imageproto_image_proto = out.File
	file_imageproto_image_proto_goTypes = nil
	file_imageproto_image_proto_depIdxs = nil
}
