FROM golang:1.26.0-alpine AS builder

WORKDIR /app

COPY go.mod go.sum* ./
RUN go mod download

COPY . .
RUN CGO_ENABLED=0 go build -o tcpserver ./cmd/tcpserver

FROM alpine:latest

WORKDIR /app

COPY --from=builder /app/tcpserver .
COPY config/practice/conn.json config/practice/conn.json

EXPOSE 3000

CMD ["./tcpserver"]
